spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sheshi396@
    url: jdbc:mysql://localhost:3306/jrtp
  jpa:
   hibernate:
      ddl-auto: update
   properties:
      hibernate:
       globally_quoted_identifiers:true
   show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: Sheshiravula396@gmail.com
    password: qhxkibpmzjtwdkhu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
     
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  profiles:
    active:
       dev
    